[package]
    name    = "wit-bindgen-wasmtime-intofunc-repro"
    version = "0.1.0"
    edition = "2021"

[dependencies]
    wit-bindgen-wasmtime = { git = "https://github.com/bytecodealliance/wit-bindgen", rev = "8fdf702982ab141c63d5b1885994306c77dbc41d" }
